name: dynamic_scaler_showcase
description: A Flutter application to showcase the usage and scope of dynamic_scaler pacakge.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dynamic_scaler:
    path: ../

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
